steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "build", "--tag=gcr.io/$PROJECT_ID/lodestone-api", "--file=./apps/lodestone-api/Dockerfile", "." ]
images:
  - 'gcr.io/$PROJECT_ID/lodestone-api'
